// <auto-generated />
using System;
using EmpMgmtDAL.EntityLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmpMgmtDAL.Migrations
{
    [DbContext(typeof(EmpMgmtDbContext))]
    [Migration("20230423150347_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EmpMgmtDAL.EntityLayer.Department", b =>
                {
                    b.Property<byte>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DeptId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DeptId = (byte)1,
                            Name = "Dept1"
                        },
                        new
                        {
                            DeptId = (byte)2,
                            Name = "Dept2"
                        });
                });

            modelBuilder.Entity("EmpMgmtDAL.EntityLayer.Employee", b =>
                {
                    b.Property<byte>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DOB")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DOJ")
                        .HasColumnType("date");

                    b.Property<byte>("DeptId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<byte>("GradeId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("EmpId");

                    b.HasIndex("DeptId");

                    b.HasIndex("GradeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmpId = (byte)1,
                            DOB = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeptId = (byte)1,
                            Email = "uemp@mail.com",
                            Gender = "M",
                            GradeId = (byte)1,
                            Name = "UEmp",
                            Password = "pass123",
                            Status = (byte)1
                        },
                        new
                        {
                            EmpId = (byte)2,
                            DOB = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeptId = (byte)2,
                            Email = "0emp@mail.com",
                            Gender = "F",
                            GradeId = (byte)2,
                            Name = "OEmp",
                            Password = "pass123",
                            Status = (byte)1
                        });
                });

            modelBuilder.Entity("EmpMgmtDAL.EntityLayer.Grade", b =>
                {
                    b.Property<byte>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .UseIdentityColumn();

                    b.Property<decimal>("Basic")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("HRA")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("TA")
                        .HasColumnType("tinyint");

                    b.HasKey("GradeId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            GradeId = (byte)1,
                            Basic = 15000m,
                            HRA = (byte)20,
                            Name = "E1",
                            TA = (byte)12
                        },
                        new
                        {
                            GradeId = (byte)2,
                            Basic = 12000m,
                            HRA = (byte)15,
                            Name = "E2",
                            TA = (byte)10
                        });
                });

            modelBuilder.Entity("EmpMgmtDAL.EntityLayer.Employee", b =>
                {
                    b.HasOne("EmpMgmtDAL.EntityLayer.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmpMgmtDAL.EntityLayer.Grade", "Grade")
                        .WithMany("Employees")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("EmpMgmtDAL.EntityLayer.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("EmpMgmtDAL.EntityLayer.Grade", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
