insert [Departments] ([Name]) values ('Dept1')
insert [Departments] ([Name]) values ('Dept2')
insert [Departments] ([Name]) values ('Dept3')

select * from Departments

insert [Grade] ([Title],[Basic],[TA],HRA)
values ('E1',15000,20,18)
insert [Grade] ([Title],[Basic],[TA],HRA)
values ('E2',12000,17,16)

insert [Employees]([Name],DOB,Gender,DeptId,GradeId,Email,[Password])
values ('IEmp','12/3/1999','F',1,1,'iemp@mail.com','pass123')

insert [Employees]([Name],DOB,Gender,DeptId,GradeId,Email,[Password])
values ('AEmp','02/7/2002','M',1,2,'aemp@mail.com','pass123')

select *from Employees

-- variables
-- @@name is a global variable, @name is a local variable
declare @name nvarchar(50)
set @name= 'Ceridian'
print @name

-- After an INSERT, SELECT, or bulk copy statement is completed, @@IDENTITY contains the last identity(Id) value that is generated by the statement
select @@IDENTITY

-- last generated Id in Departments table
select IDENT_CURRENT('Departments')